services:
  ollama:
    container_name: ollama
    ports:
      - "11434:11434"
    build:
        context: .
        dockerfile: Dockerfile.ollama
    entrypoint: ["/usr/bin/bash", "/pull-llama3.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - ollama_network
    volumes:
        - ollama_models:/root/.ollama
  fastapi:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - AUTH_TOKEN_NGROK=${AUTH_TOKEN_NGROK}
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - ollama 
    env_file: ".env"
    volumes:
      - .:/app
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge

volumes:
  ollama_models:
    driver: local